export const cardArray: any[] = [
    {
        "cardClass": "WARRIOR",
        "collectible": true,
        "dbfId": 7,
        "health": 30,
        "id": "HERO_01",
        "name": "Garrosh Hellscream",
        "rarity": "FREE",
        "set": "CORE",
        "type": "HERO"
    },
    {
        "cardClass": "SHAMAN",
        "collectible": true,
        "dbfId": 1066,
        "health": 30,
        "id": "HERO_02",
        "name": "Thrall",
        "rarity": "FREE",
        "set": "CORE",
        "type": "HERO"
    },
    {
        "attack": 4,
        "cardClass": "NEUTRAL",
        "cost": 1,
        "dbfId": 2543,
        "health": 2,
        "id": "AT_005t",
        "mechanics": [
            "CHARGE"
        ],
        "name": "Boar",
        "race": "BEAST",
        "set": "TGT",
        "text": "<b>Charge</b>",
        "type": "MINION"
    },
    {
        "artist": "Arthur Bozonnet",
        "attack": 3,
        "cardClass": "MAGE",
        "collectible": true,
        "cost": 1,
        "dbfId": 2545,
        "flavor": "And he can't get up.",
        "health": 2,
        "id": "AT_003",
        "mechanics": [
            "HEROPOWER_DAMAGE"
        ],
        "name": "Fallen Hero",
        "rarity": "RARE",
        "set": "TGT",
        "text": "Your Hero Power deals 1 extra damage.",
        "type": "MINION"
    },
    {
        "artist": "Tooth",
        "attack": 2,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 3,
        "dbfId": 339,
        "faction": "ALLIANCE",
        "flavor": "\"Ready! Aim! Drink!\"",
        "health": 2,
        "howToEarnGolden": "Unlocked at Mage Level 55.",
        "id": "CS2_141",
        "mechanics": [
            "BATTLECRY"
        ],
        "name": "Ironforge Rifleman",
        "rarity": "FREE",
        "set": "CORE",
        "targetingArrowText": "Deal 1 damage.",
        "text": "<b>Battlecry:</b> Deal 1 damage.",
        "type": "MINION"
    },
    {
        "artist": "Matt Cavotta",
        "attack": 5,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 5,
        "dbfId": 1140,
        "faction": "HORDE",
        "flavor": "You can hire him... until someone offers him enough gold to turn on you.",
        "health": 4,
        "howToEarnGolden": "Unlocked at Shaman Level 55.",
        "id": "CS2_187",
        "mechanics": [
            "TAUNT"
        ],
        "name": "Booty Bay Bodyguard",
        "rarity": "FREE",
        "set": "CORE",
        "text": "<b>Taunt</b>",
        "type": "MINION"
    },
    {
        "artist": "Steve Prescott",
        "attack": 1,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 1,
        "dbfId": 389,
        "faction": "HORDE",
        "flavor": "Don't bother asking her out on a date.  She'll shoot you down.",
        "health": 1,
        "howToEarnGolden": "Unlocked at Druid Level 57.",
        "id": "CS2_189",
        "mechanics": [
            "BATTLECRY"
        ],
        "name": "Elven Archer",
        "rarity": "FREE",
        "set": "CORE",
        "targetingArrowText": "Deal 1 damage.",
        "text": "<b>Battlecry:</b> Deal 1 damage.",
        "type": "MINION"
    },
    {
        "artist": "Richie Marella",
        "attack": 2,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 2,
        "dbfId": 41,
        "flavor": "Grunting is what his father did and his father before that.   It's more than just a job.",
        "health": 2,
        "howToEarnGolden": "Unlocked at Shaman Level 57.",
        "id": "CS2_121",
        "mechanics": [
            "TAUNT"
        ],
        "name": "Frostwolf Grunt",
        "rarity": "FREE",
        "set": "CORE",
        "text": "<b>Taunt</b>",
        "type": "MINION"
    },
    {
        "artist": "Court Jones",
        "attack": 2,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 4,
        "dbfId": 308,
        "faction": "ALLIANCE",
        "flavor": "She's never quite sure what she's making, she just knows it's AWESOME!",
        "health": 4,
        "howToEarnGolden": "Unlocked at Priest Level 57.",
        "id": "CS2_147",
        "mechanics": [
            "BATTLECRY"
        ],
        "name": "Gnomish Inventor",
        "rarity": "FREE",
        "set": "CORE",
        "text": "<b>Battlecry:</b> Draw a card.",
        "type": "MINION"
    },
    {
        "artist": "Nutthapon Petchthai",
        "cardClass": "MAGE",
        "collectible": true,
        "cost": 1,
        "dbfId": 2539,
        "flavor": "It's on the rack next to ice lance, acid lance, and English muffin lance.",
        "id": "AT_001",
        "name": "Flame Lance",
        "rarity": "COMMON",
        "set": "TGT",
        "text": "Increase 1 damage of player's minions on battlefield.",
        "type": "SPELL"
    },
    {
        "artist": "Tooth",
        "cardClass": "MAGE",
        "collectible": true,
        "cost": 1,
        "dbfId": 2541,
        "flavor": "Burning man, brah.",
        "id": "AT_002",
        "mechanics": [
            "SECRET"
        ],
        "name": "Effigy",
        "rarity": "RARE",
        "set": "TGT",
        "text": "Decrease cost of all cards in player's hand by 1 cost.",
        "type": "SPELL"
    },
    {
        "artist": "New Tooth",
        "cardClass": "MAGE",
        "collectible": true,
        "cost": 1,
        "dbfId": 2541,
        "flavor": "Burning man, brah.",
        "id": "AT_004",
        "name": "Danger",
        "rarity": "RARE",
        "set": "TGT",
        "text": "Increase 1 health of the hero and damage 1 to each enemy on battle ground.",
        "type": "SPELL"
    },
    {
        "artist": "Lars Grant-West",
        "attack": 3,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 3,
        "dbfId": 1182,
        "flavor": "\"Bear Carcass 1/10\"",
        "health": 3,
        "howToEarnGolden": "Unlocked at Hunter Level 59.",
        "id": "CS2_125",
        "mechanics": [
            "TAUNT"
        ],
        "name": "Ironfur Grizzly",
        "race": "BEAST",
        "rarity": "FREE",
        "set": "CORE",
        "text": "<b>Taunt</b>",
        "type": "MINION"
    },
    {
        "artist": "Mauro Cascioli",
        "attack": 4,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 4,
        "dbfId": 90,
        "flavor": "He always dreamed of coming down from the mountains and opening a noodle shop, but he never got the nerve.",
        "health": 5,
        "howToEarnGolden": "Unlocked at Warrior Level 55.",
        "id": "CS2_182",
        "name": "Chillwind Yeti",
        "rarity": "FREE",
        "set": "CORE",
        "type": "MINION"
    },
    {
        "artist": "Luca Zontini",
        "attack": 1,
        "cardClass": "NEUTRAL",
        "collectible": true,
        "cost": 1,
        "dbfId": 242,
        "faction": "ALLIANCE",
        "flavor": "ADD ME TO YOUR DECK, MAGGOT!",
        "health": 1,
        "id": "CS2_188",
        "mechanics": [
            "BATTLECRY"
        ],
        "name": "Abusive Sergeant",
        "rarity": "COMMON",
        "set": "EXPERT1",
        "targetingArrowText": "Give +2 Attack this turn.",
        "text": "<b>Battlecry:</b> Give a minion +2 Attack this turn.",
        "type": "MINION"
    },
    {
        "artist": "Mike Sass",
        "cardClass": "PRIEST",
        "collectible": true,
        "cost": 1,
        "dbfId": 2568,
        "flavor": "The promise of glory is a powerful tool to get minions to do your bidding.  Only slightly less powerful than the promise of an ice cream bar!",
        "id": "AT_013",
        "name": "Power Word: Glory",
        "rarity": "COMMON",
        "set": "TGT",
        "text": "Summon 2/2 minion for each card on hand.",
        "type": "SPELL"
    },
    {
        "artist": "Dan Dos Santos",
        "cardClass": "PRIEST",
        "collectible": true,
        "cost": 2,
        "dbfId": 2563,
        "flavor": "\"Are you interested in... HEALTH benefits?!\"",
        "id": "AT_015",
        "name": "Convert",
        "rarity": "RARE",
        "set": "TGT",
        "text": "Deal 3 damage for all opponent's card on the battlefield.",
        "type": "SPELL"
    },
    {
        "artist": "Sean O’Daniels",
        "cardClass": "PRIEST",
        "collectible": true,
        "cost": 2,
        "dbfId": 2564,
        "flavor": "This minion is really powerful!",
        "id": "AT_016",
        "name": "Confuse",
        "rarity": "EPIC",
        "set": "TGT",
        "text": "Increase Hero's mana by 5.",
        "type": "SPELL"
    }
]
